/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import basicas.Locacao;
import basicas.Veiculo;
import dao.ConexaoMySql;
import dao.DAOLocacao;
import dao.DAOVeiculo;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author 201710040006
 */
public class DialogLocacao extends javax.swing.JDialog {

    DAOLocacao dao;
    InternalLocacao frameAnterior;
    Locacao locacao;
    int posicao;
    SimpleDateFormat forma = new SimpleDateFormat("dd-MM-yyyy HH:mm:ss");

    public DialogLocacao(InternalLocacao frameAnterior, boolean isNovo) {
        //super(parent, modal);
        initComponents();
        dao = new DAOLocacao();
        this.frameAnterior = frameAnterior;

        if (isNovo) {
            limparFormulario();
        } else {
            posicao = this.frameAnterior.getTabela().getSelectedRow();
            locacao = this.frameAnterior.getAllLocacoes().get(posicao);  
            atualizarFormulario();
        }
        
        preencherComboVeiculos();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bNovo = new javax.swing.JButton();
        bSalvar = new javax.swing.JButton();
        bEscluir = new javax.swing.JButton();
        bPrimeiro = new javax.swing.JButton();
        bAnterior = new javax.swing.JButton();
        bProximo = new javax.swing.JButton();
        bUltimo = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        tfCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfDataEntrega = new javax.swing.JTextField();
        tfDataDevolucao = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbStatus = new javax.swing.JComboBox<>();
        cbVeiculo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Formulário Veiculos");
        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Locações"));

        bNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/new2_32.png"))); // NOI18N
        bNovo.setBorderPainted(false);
        bNovo.setContentAreaFilled(false);
        bNovo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/new3_32.png"))); // NOI18N
        bNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNovoActionPerformed(evt);
            }
        });

        bSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/save_32.png"))); // NOI18N
        bSalvar.setBorderPainted(false);
        bSalvar.setContentAreaFilled(false);
        bSalvar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/folder2_32.png"))); // NOI18N
        bSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalvarActionPerformed(evt);
            }
        });

        bEscluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/delete_32.png"))); // NOI18N
        bEscluir.setBorderPainted(false);
        bEscluir.setContentAreaFilled(false);
        bEscluir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/delete2_32.png"))); // NOI18N
        bEscluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEscluirActionPerformed(evt);
            }
        });

        bPrimeiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/backwardFirst_32.png"))); // NOI18N
        bPrimeiro.setBorderPainted(false);
        bPrimeiro.setContentAreaFilled(false);
        bPrimeiro.setRolloverEnabled(false);
        bPrimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPrimeiroActionPerformed(evt);
            }
        });

        bAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/backward_32.png"))); // NOI18N
        bAnterior.setBorderPainted(false);
        bAnterior.setContentAreaFilled(false);
        bAnterior.setRolloverEnabled(false);
        bAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAnteriorActionPerformed(evt);
            }
        });

        bProximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/forward_32.png"))); // NOI18N
        bProximo.setBorderPainted(false);
        bProximo.setContentAreaFilled(false);
        bProximo.setRolloverEnabled(false);
        bProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bProximoActionPerformed(evt);
            }
        });

        bUltimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/forwardEnd_32.png"))); // NOI18N
        bUltimo.setBorderPainted(false);
        bUltimo.setContentAreaFilled(false);
        bUltimo.setRolloverEnabled(false);
        bUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUltimoActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(bNovo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bEscluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bPrimeiro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bAnterior)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bProximo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bUltimo)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bEscluir)
                    .addComponent(bSalvar)
                    .addComponent(bNovo)
                    .addComponent(bPrimeiro)
                    .addComponent(bAnterior)
                    .addComponent(bProximo)
                    .addComponent(bUltimo))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel1.setText("Código:");

        tfCodigo.setEditable(false);

        jLabel2.setText("Data de Entrega:");

        jLabel3.setText("Data de Devolução: ");

        jLabel4.setText("Status:");

        jLabel5.setText("Veículo:");

        cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Em Uso", "Cancelada", "Encerrada" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(tfDataEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(tfDataDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel5)
                    .addComponent(cbVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(tfDataEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tfDataDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(26, 26, 26)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(221, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNovoActionPerformed
        limparFormulario();
    }//GEN-LAST:event_bNovoActionPerformed

    private void bSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalvarActionPerformed
        Locacao loca = new Locacao();
        loca.setId(Integer.parseInt(tfCodigo.getText()));
        
        try {
            loca.setDataDevolucao(forma.parse(tfDataDevolucao.getText()));
            loca.setDataEntrega(forma.parse(tfDataEntrega.getText())); 
        } catch (ParseException ex) {
            System.out.println("Erro no formato de data!");
        }
        
        loca.setStatus(cbStatus.getSelectedItem().toString());
        Veiculo vei = (Veiculo) cbVeiculo.getSelectedItem();
        loca.setVeiculo(vei);

        if (tfCodigo.getText().isEmpty()) {
            dao.inserirLocacao(loca);
            frameAnterior.setAllLocacoes(dao.getAllLocacoes(frameAnterior.getOrdena()));
            frameAnterior.preencherTabela();
            posicao = frameAnterior.getAllLocacoes().size() - 1;
            locacao = frameAnterior.getAllLocacoes().get(posicao);
            JOptionPane.showMessageDialog(this, "Salvo com Sucesso");
        } else {
            vei.setId(Integer.parseInt(tfCodigo.getText()));
            dao.atualizarLocacao(loca);
            frameAnterior.setAllLocacoes(dao.getAllLocacoes(frameAnterior.getOrdena()));
            frameAnterior.preencherTabela();
            locacao = frameAnterior.getAllLocacoes().get(posicao);
            JOptionPane.showMessageDialog(this, "Atualizado com Sucesso");
        }

        atualizarFormulario();

    }//GEN-LAST:event_bSalvarActionPerformed

    private void bPrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPrimeiroActionPerformed
        posicao = 0;
        locacao = frameAnterior.getAllLocacoes().get(posicao);
        frameAnterior.getTabela().setRowSelectionInterval(posicao, posicao);
        atualizarFormulario();
    }//GEN-LAST:event_bPrimeiroActionPerformed

    private void bUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUltimoActionPerformed
        posicao = frameAnterior.getAllLocacoes().size() - 1;
        locacao = frameAnterior.getAllLocacoes().get(posicao);
        frameAnterior.getTabela().setRowSelectionInterval(posicao, posicao);
        atualizarFormulario();
    }//GEN-LAST:event_bUltimoActionPerformed

    private void bAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAnteriorActionPerformed
        posicao--;
        if (posicao < 0) {
            JOptionPane.showMessageDialog(this, "Já está no Primeiro Registro!");
            posicao++;
        } else {
            locacao = frameAnterior.getAllLocacoes().get(posicao);
            frameAnterior.getTabela().setRowSelectionInterval(posicao, posicao);
            atualizarFormulario();
        }


    }//GEN-LAST:event_bAnteriorActionPerformed

    private void bProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bProximoActionPerformed
        posicao++;
        if (posicao > frameAnterior.getAllLocacoes().size() - 1) {
            JOptionPane.showMessageDialog(this, "Já está no Derradero Registro!");
            posicao--;
        } else {
            locacao = frameAnterior.getAllLocacoes().get(posicao);
            frameAnterior.getTabela().setRowSelectionInterval(posicao, posicao);
            atualizarFormulario();
        }
    }//GEN-LAST:event_bProximoActionPerformed

    private void bEscluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEscluirActionPerformed

        int opcao = JOptionPane.showConfirmDialog(this, "Tem certeza?", "Alerta!", JOptionPane.YES_NO_OPTION);
        if (opcao == 0) { //0 é sim, 1 é não e 2 é cancelar
            dao.deletarLocacao(locacao);
            frameAnterior.setAllLocacoes(dao.getAllLocacoes(frameAnterior.getOrdena()));
            frameAnterior.preencherTabela();
            if (posicao > 0) {
                posicao--;
            }
            locacao = frameAnterior.getAllLocacoes().get(posicao);
            atualizarFormulario();
            JOptionPane.showMessageDialog(this, "Excluído com sucesso!");
        }

    }//GEN-LAST:event_bEscluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogLocacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogLocacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogLocacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogLocacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogLocacao dialog = new DialogLocacao(null, true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAnterior;
    private javax.swing.JButton bEscluir;
    private javax.swing.JButton bNovo;
    private javax.swing.JButton bPrimeiro;
    private javax.swing.JButton bProximo;
    private javax.swing.JButton bSalvar;
    private javax.swing.JButton bUltimo;
    private javax.swing.JComboBox<String> cbStatus;
    private javax.swing.JComboBox<Veiculo> cbVeiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField tfCodigo;
    private javax.swing.JTextField tfDataDevolucao;
    private javax.swing.JTextField tfDataEntrega;
    // End of variables declaration//GEN-END:variables

    public void atualizarFormulario() {
        tfCodigo.setText(""+locacao.getId());
        tfDataDevolucao.setText(forma.format(locacao.getDataDevolucao()));
        tfDataEntrega.setText(forma.format(locacao.getDataEntrega()));
        cbStatus.setSelectedItem(locacao.getStatus());
        
        cbVeiculo.setSelectedItem(locacao.getVeiculo());  
        
    }

    public void limparFormulario() {
        posicao = -1;

    }
    
    public void preencherComboVeiculos(){
        DAOVeiculo daoVeiculo = new DAOVeiculo();
        ArrayList<Veiculo> listaVeiculos = daoVeiculo.getAllVeiculos("veiculo_id");
        
        for(Veiculo v : listaVeiculos){
            cbVeiculo.addItem(v);
        } 
    }
}
