package view;

import controller.DAOFuncionario;
import java.awt.Rectangle;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Cargo;
import model.Funcionario;

public class FrameFuncionario extends javax.swing.JFrame {

    private DAOFuncionario dao;
    private List<Funcionario> lista;
    private int posicao;
    private String ordenacao;
    private Cargo cargo;

    public FrameFuncionario() {
        initComponents();

        posicao = 0;
        ordenacao = "funci_id";
        dao = new DAOFuncionario();
        lista = dao.getAllFuncionarios(ordenacao);
        preencherTabela();
        preencherFrame();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        painelManter = new javax.swing.JPanel();
        botaoNovo = new javax.swing.JButton();
        botaoSalvar = new javax.swing.JButton();
        botaoAtualizar = new javax.swing.JButton();
        botaoExcluir = new javax.swing.JButton();
        textoFiltrar = new javax.swing.JTextField();
        botaoFiltrar = new javax.swing.JButton();
        comboFiltrar = new javax.swing.JComboBox<>();
        botaoAnterior = new javax.swing.JButton();
        botaoPrimeiro = new javax.swing.JButton();
        botaoUltimo = new javax.swing.JButton();
        botaoProximo = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        botaoLimparFiltrar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        textoCodigo = new javax.swing.JTextField();
        textoNome = new javax.swing.JTextField();
        textoCpf = new javax.swing.JTextField();
        comboSexo = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        radioNome = new javax.swing.JRadioButton();
        radioCodigo = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textoCodigoCargo = new javax.swing.JTextField();
        textoNomeCargo = new javax.swing.JTextField();
        botaoAdicionarCargo = new javax.swing.JButton();
        botaoExcluirCargo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Funcionários");

        painelManter.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        botaoNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/new2_32.png"))); // NOI18N
        botaoNovo.setToolTipText("Novo");
        botaoNovo.setBorder(null);
        botaoNovo.setBorderPainted(false);
        botaoNovo.setContentAreaFilled(false);
        botaoNovo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoNovo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/new3_32.png"))); // NOI18N
        botaoNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoNovoActionPerformed(evt);
            }
        });

        botaoSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/save_32.png"))); // NOI18N
        botaoSalvar.setToolTipText("Salvar");
        botaoSalvar.setBorder(null);
        botaoSalvar.setContentAreaFilled(false);
        botaoSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoSalvar.setEnabled(false);
        botaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarActionPerformed(evt);
            }
        });

        botaoAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/refresh_32.png"))); // NOI18N
        botaoAtualizar.setToolTipText("Atualizar");
        botaoAtualizar.setBorder(null);
        botaoAtualizar.setContentAreaFilled(false);
        botaoAtualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAtualizarActionPerformed(evt);
            }
        });

        botaoExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/delete_32.png"))); // NOI18N
        botaoExcluir.setToolTipText("Excluir");
        botaoExcluir.setBorder(null);
        botaoExcluir.setContentAreaFilled(false);
        botaoExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoExcluir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/delete2_32.png"))); // NOI18N
        botaoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirActionPerformed(evt);
            }
        });

        textoFiltrar.setToolTipText("Digite para Filtrar");
        textoFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoFiltrarActionPerformed(evt);
            }
        });

        botaoFiltrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/filter_32.png"))); // NOI18N
        botaoFiltrar.setToolTipText("Filtrar");
        botaoFiltrar.setBorder(null);
        botaoFiltrar.setContentAreaFilled(false);
        botaoFiltrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoFiltrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/filter2_32.png"))); // NOI18N
        botaoFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFiltrarActionPerformed(evt);
            }
        });

        comboFiltrar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nome", "Código" }));
        comboFiltrar.setToolTipText("Filtrar Por");

        botaoAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/backward_32.png"))); // NOI18N
        botaoAnterior.setToolTipText("Anterior");
        botaoAnterior.setBorder(null);
        botaoAnterior.setContentAreaFilled(false);
        botaoAnterior.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoAnterior.setEnabled(false);
        botaoAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAnteriorActionPerformed(evt);
            }
        });

        botaoPrimeiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/backwardFirst_32.png"))); // NOI18N
        botaoPrimeiro.setToolTipText("Primeiro");
        botaoPrimeiro.setBorder(null);
        botaoPrimeiro.setContentAreaFilled(false);
        botaoPrimeiro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoPrimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPrimeiroActionPerformed(evt);
            }
        });

        botaoUltimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/forwardEnd_32.png"))); // NOI18N
        botaoUltimo.setToolTipText("Último");
        botaoUltimo.setBorder(null);
        botaoUltimo.setContentAreaFilled(false);
        botaoUltimo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoUltimoActionPerformed(evt);
            }
        });

        botaoProximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/forward_32.png"))); // NOI18N
        botaoProximo.setToolTipText("Próximo");
        botaoProximo.setBorder(null);
        botaoProximo.setContentAreaFilled(false);
        botaoProximo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoProximoActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(153, 153, 153));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator2.setForeground(new java.awt.Color(153, 153, 153));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        botaoLimparFiltrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/eraser2_32.png"))); // NOI18N
        botaoLimparFiltrar.setToolTipText("Limpar Filtro e Listar Tudo");
        botaoLimparFiltrar.setBorder(null);
        botaoLimparFiltrar.setBorderPainted(false);
        botaoLimparFiltrar.setContentAreaFilled(false);
        botaoLimparFiltrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoLimparFiltrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/eraser3_32.png"))); // NOI18N
        botaoLimparFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLimparFiltrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelManterLayout = new javax.swing.GroupLayout(painelManter);
        painelManter.setLayout(painelManterLayout);
        painelManterLayout.setHorizontalGroup(
            painelManterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelManterLayout.createSequentialGroup()
                .addComponent(botaoNovo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoAtualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoPrimeiro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoAnterior)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoProximo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoUltimo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(botaoFiltrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoLimparFiltrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelManterLayout.setVerticalGroup(
            painelManterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelManterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelManterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(painelManterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(botaoFiltrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoAnterior)
                        .addComponent(botaoPrimeiro)
                        .addComponent(botaoProximo)
                        .addComponent(botaoUltimo)
                        .addGroup(painelManterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botaoNovo)
                            .addComponent(botaoSalvar)
                            .addComponent(botaoAtualizar)
                            .addComponent(botaoExcluir))
                        .addGroup(painelManterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textoFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(botaoLimparFiltrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jLabel4.setText("Código:");
        jPanel1.add(jLabel4);

        jLabel5.setText("* Nome:");
        jPanel1.add(jLabel5);

        jLabel6.setText("CPF:");
        jPanel1.add(jLabel6);

        jLabel7.setText("Sexo:");
        jPanel1.add(jLabel7);

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        textoCodigo.setEditable(false);
        jPanel2.add(textoCodigo);

        textoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoNomeActionPerformed(evt);
            }
        });
        jPanel2.add(textoNome);

        textoCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoCpfActionPerformed(evt);
            }
        });
        jPanel2.add(textoCpf);

        comboSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino" }));
        jPanel2.add(comboSexo);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Ordenar"));

        buttonGroup1.add(radioNome);
        radioNome.setText("Nome");
        radioNome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        radioNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNomeActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioCodigo);
        radioCodigo.setSelected(true);
        radioCodigo.setText("Código");
        radioCodigo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        radioCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioCodigoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radioCodigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioNome)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(radioCodigo)
                .addComponent(radioNome))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "CPF", "Sexo", "Cargo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setSurrendersFocusOnKeystroke(true);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Cargo"));

        jLabel1.setText("Código:");

        jLabel2.setText("Nome:");

        textoCodigoCargo.setEditable(false);

        textoNomeCargo.setEditable(false);

        botaoAdicionarCargo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/new2_32.png"))); // NOI18N
        botaoAdicionarCargo.setToolTipText("Novo");
        botaoAdicionarCargo.setBorder(null);
        botaoAdicionarCargo.setBorderPainted(false);
        botaoAdicionarCargo.setContentAreaFilled(false);
        botaoAdicionarCargo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoAdicionarCargo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/new3_32.png"))); // NOI18N
        botaoAdicionarCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAdicionarCargoActionPerformed(evt);
            }
        });

        botaoExcluirCargo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/delete_32.png"))); // NOI18N
        botaoExcluirCargo.setToolTipText("Excluir");
        botaoExcluirCargo.setBorder(null);
        botaoExcluirCargo.setContentAreaFilled(false);
        botaoExcluirCargo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoExcluirCargo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/delete2_32.png"))); // NOI18N
        botaoExcluirCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirCargoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoCodigoCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(textoNomeCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoAdicionarCargo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoExcluirCargo)))
                .addContainerGap(619, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botaoAdicionarCargo)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textoCodigoCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textoNomeCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(botaoExcluirCargo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(painelManter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelManter, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarActionPerformed
        Funcionario func = new Funcionario();
        func.setNome(textoNome.getText());
        func.setCpf(textoCpf.getText());
        func.setSexo(comboSexo.getSelectedItem().toString());
        func.setCargo(cargo);

        boolean status = dao.insertFuncionario(func);

        if (status == true) {
            JOptionPane.showMessageDialog(this, "Salvo com sucesso!");
            int opcao = JOptionPane.showConfirmDialog(this, "Deseja salvar outro Funcionário?", "Mensagem", JOptionPane.YES_NO_OPTION);

            if (opcao == 0) {
                limparFrame();
            } else {
                lista = dao.getAllFuncionarios(ordenacao);
                posicao = lista.size() - 1;
                preencherTabela();
                preencherFrame();
                botaoSalvar.setEnabled(false);
                botaoAtualizar.setEnabled(true);
                botaoExcluir.setEnabled(true);
            }

        } else {
            JOptionPane.showMessageDialog(this, "Erro ao salvar!");
        }


    }//GEN-LAST:event_botaoSalvarActionPerformed

    private void textoFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoFiltrarActionPerformed

    }//GEN-LAST:event_textoFiltrarActionPerformed

    private void botaoAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAnteriorActionPerformed
        posicao--;

//        if (posicao == 0) {
//            botaoAnterior.setEnabled(false);
//            botaoPrimeiro.setEnabled(false);
//        }
        preencherFrame();
//        botaoProximo.setEnabled(true);
//        botaoUltimo.setEnabled(true);


    }//GEN-LAST:event_botaoAnteriorActionPerformed

    private void botaoUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoUltimoActionPerformed
        posicao = lista.size() - 1;
        preencherFrame();

//        botaoAnterior.setEnabled(true);
//        botaoPrimeiro.setEnabled(true);
//        botaoProximo.setEnabled(false);
//        botaoUltimo.setEnabled(false);
    }//GEN-LAST:event_botaoUltimoActionPerformed

    private void botaoProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoProximoActionPerformed
        posicao++;

//        if (posicao == lista.size() - 1) {
//            botaoProximo.setEnabled(false);
//            botaoUltimo.setEnabled(false);
//        }
        preencherFrame();
//        botaoAnterior.setEnabled(true);
//        botaoPrimeiro.setEnabled(true);

    }//GEN-LAST:event_botaoProximoActionPerformed

    private void botaoNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoNovoActionPerformed
        limparFrame();
    }//GEN-LAST:event_botaoNovoActionPerformed

    private void botaoAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAtualizarActionPerformed
        Funcionario func = new Funcionario();
        func.setId(Integer.parseInt(textoCodigo.getText()));
        func.setNome(textoNome.getText());
        func.setCpf(textoCpf.getText());
        func.setSexo(comboSexo.getSelectedItem().toString());
        func.setCargo(cargo);

        if (dao.atualizarFuncionario(func)) {
            lista = dao.getAllFuncionarios(ordenacao);
            preencherTabela();
            preencherFrame();
            JOptionPane.showMessageDialog(this, "Atualizado com sucesso!");
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao atualizar!");
        }

    }//GEN-LAST:event_botaoAtualizarActionPerformed

    private void botaoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirActionPerformed
        boolean status = dao.deletarFuncionario(Integer.parseInt(textoCodigo.getText()));

        if (status == true) {
            lista = dao.getAllFuncionarios(ordenacao);
            posicao = 0;
            preencherTabela();
            preencherFrame();
            JOptionPane.showMessageDialog(this, "Excluído com sucesso!");
        } else {
            JOptionPane.showMessageDialog(this, "Não foi possível excluir!");
        }

    }//GEN-LAST:event_botaoExcluirActionPerformed

    private void textoCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoCpfActionPerformed

    }//GEN-LAST:event_textoCpfActionPerformed

    private void botaoPrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPrimeiroActionPerformed
        posicao = 0;
        preencherFrame();

//        botaoAnterior.setEnabled(false);
//        botaoPrimeiro.setEnabled(false);
//        botaoProximo.setEnabled(true);
//        botaoUltimo.setEnabled(true);
    }//GEN-LAST:event_botaoPrimeiroActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        posicao = jTable1.getSelectedRow();
        preencherFrame();
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased

    }//GEN-LAST:event_jTable1KeyReleased

    private void radioCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioCodigoActionPerformed
        ordenacao = "funci_id";
        lista = dao.getAllFuncionarios(ordenacao);
        posicao = 0;
        preencherTabela();
        preencherFrame();

    }//GEN-LAST:event_radioCodigoActionPerformed

    private void radioNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNomeActionPerformed
        ordenacao = "funci_nome";
        lista = dao.getAllFuncionarios(ordenacao);
        posicao = 0;
        preencherTabela();
        preencherFrame();

    }//GEN-LAST:event_radioNomeActionPerformed

    private void botaoFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFiltrarActionPerformed
        String campo = comboFiltrar.getSelectedItem().toString();
        if (campo.equals("Nome")) {
            campo = "funci_nome";
        } else {
            campo = "funci_id";
        }

        String valor = textoFiltrar.getText();

        List<Funcionario> listaTemporaria = dao.getFiltrarFuncionarios(campo, valor, ordenacao);

        if (listaTemporaria.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ops! não encontrei nada!");
        } else {
            lista = listaTemporaria;
            posicao = 0;
            preencherTabela();
            preencherFrame();
        }

        textoFiltrar.setText("");

    }//GEN-LAST:event_botaoFiltrarActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed

    }//GEN-LAST:event_formInternalFrameClosed

    private void botaoLimparFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLimparFiltrarActionPerformed
        lista = dao.getAllFuncionarios(ordenacao);
        posicao = 0;
        preencherTabela();
        preencherFrame();
        textoFiltrar.setText("");
    }//GEN-LAST:event_botaoLimparFiltrarActionPerformed

    private void textoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoNomeActionPerformed

    private void botaoAdicionarCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAdicionarCargoActionPerformed
        new DialogCargo(this, true, this).setVisible(true);
    }//GEN-LAST:event_botaoAdicionarCargoActionPerformed

    private void botaoExcluirCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirCargoActionPerformed
        textoCodigoCargo.setText("");
        textoNomeCargo.setText("");
        cargo = null;
    }//GEN-LAST:event_botaoExcluirCargoActionPerformed

    public static void main(String args[]) {
        new FrameFuncionario().setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAdicionarCargo;
    private javax.swing.JButton botaoAnterior;
    private javax.swing.JButton botaoAtualizar;
    private javax.swing.JButton botaoExcluir;
    private javax.swing.JButton botaoExcluirCargo;
    private javax.swing.JButton botaoFiltrar;
    private javax.swing.JButton botaoLimparFiltrar;
    private javax.swing.JButton botaoNovo;
    private javax.swing.JButton botaoPrimeiro;
    private javax.swing.JButton botaoProximo;
    private javax.swing.JButton botaoSalvar;
    private javax.swing.JButton botaoUltimo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comboFiltrar;
    private javax.swing.JComboBox<String> comboSexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel painelManter;
    private javax.swing.JRadioButton radioCodigo;
    private javax.swing.JRadioButton radioNome;
    private javax.swing.JTextField textoCodigo;
    private javax.swing.JTextField textoCodigoCargo;
    private javax.swing.JTextField textoCpf;
    private javax.swing.JTextField textoFiltrar;
    private javax.swing.JTextField textoNome;
    private javax.swing.JTextField textoNomeCargo;
    // End of variables declaration//GEN-END:variables

    private void preencherFrame() {
        Funcionario func = lista.get(posicao);
        textoCodigo.setText("" + func.getId());
        textoNome.setText(func.getNome());
        textoCpf.setText(func.getCpf());
        comboSexo.setSelectedItem(func.getSexo());

        if (func.getCargo() != null) {
            textoCodigoCargo.setText("" + func.getCargo().getId());
            textoNomeCargo.setText(func.getCargo().getNome());
        } else {
            textoCodigoCargo.setText("");
            textoNomeCargo.setText("");
        }

        jTable1.setRowSelectionInterval(posicao, posicao);

        int linhaSelecionada = jTable1.getSelectedRow();
        Rectangle retanguloVisivel = jTable1.getCellRect(linhaSelecionada, 0, true);
        jTable1.scrollRectToVisible(retanguloVisivel);

        botaoExcluir.setEnabled(true);
        botaoAtualizar.setEnabled(true);
        botaoSalvar.setEnabled(false);

        if (posicao == 0) {
            botaoAnterior.setEnabled(false);
            botaoPrimeiro.setEnabled(false);
            botaoProximo.setEnabled(true);
            botaoUltimo.setEnabled(true);
        } else if (posicao == lista.size() - 1) {
            botaoAnterior.setEnabled(true);
            botaoPrimeiro.setEnabled(true);
            botaoProximo.setEnabled(false);
            botaoUltimo.setEnabled(false);
        } else {
            botaoAnterior.setEnabled(true);
            botaoPrimeiro.setEnabled(true);
            botaoProximo.setEnabled(true);
            botaoUltimo.setEnabled(true);
        }
    }

    private void limparFrame() {
        botaoSalvar.setEnabled(true);
        botaoAtualizar.setEnabled(false);
        botaoExcluir.setEnabled(false);

        textoCodigo.setText("");
        textoNome.setText("");
        textoCpf.setText("");

        textoNome.requestFocus();

        textoCodigoCargo.setText("");
        textoNomeCargo.setText("");
        cargo = null;
    }

    private void preencherTabela() {
        DefaultTableModel modeloTabela = (DefaultTableModel) jTable1.getModel();
        modeloTabela.setNumRows(0);

        Object[] linha;

        for (Funcionario func : lista) {

            linha = new Object[]{func.getId(), func.getNome(), func.getCpf(), func.getSexo(), func.getCargo() == null ? "" : func.getCargo().getNome()};

            modeloTabela.addRow(linha);
        }

        jTable1.setRowSelectionInterval(posicao, posicao);

    }

    public void receberCargo(Cargo cargo) {
        this.cargo = cargo;
        textoCodigoCargo.setText("" + cargo.getId());
        textoNomeCargo.setText(cargo.getNome());
    }

}
