/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.DAOFuncao;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.Funcao;

/**
 *
 * @author eliomar.campos
 */
public class DialogFuncao extends javax.swing.JDialog {

    private DAOFuncao dao;
    private List<Funcao> listaFuncoes;
    private Funcao funcao;
    private int posicao;
    private InternalFuncao parent;

    public DialogFuncao(InternalFuncao parent, boolean novo) {
        super();
        initComponents();
        this.parent = parent;
        dao = new DAOFuncao();
        listaFuncoes = parent.getListaFuncoes();

        if (novo) {
            limparFormulario();
        } else {
            posicao = parent.getjTable1().getSelectedRow();
            funcao = listaFuncoes.isEmpty() ? null : listaFuncoes.get(posicao);
            atualizarFormulario();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelManter = new javax.swing.JPanel();
        botaoNovo = new javax.swing.JButton();
        botaoSalvar = new javax.swing.JButton();
        botaoExcluir = new javax.swing.JButton();
        botaoAnterior = new javax.swing.JButton();
        botaoPrimeiro = new javax.swing.JButton();
        botaoUltimo = new javax.swing.JButton();
        botaoProximo = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        tfCodigo = new javax.swing.JTextField();
        tfNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Formulário - Funções");
        setIconImage(new ImageIcon(getClass().getResource("/view/img/cargos_24.png")).getImage());
        setModal(true);

        painelManter.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        botaoNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/new2_32.png"))); // NOI18N
        botaoNovo.setToolTipText("Novo");
        botaoNovo.setBorder(null);
        botaoNovo.setBorderPainted(false);
        botaoNovo.setContentAreaFilled(false);
        botaoNovo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoNovo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/new3_32.png"))); // NOI18N
        botaoNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoNovoActionPerformed(evt);
            }
        });

        botaoSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/save_32.png"))); // NOI18N
        botaoSalvar.setToolTipText("Gravar");
        botaoSalvar.setBorder(null);
        botaoSalvar.setContentAreaFilled(false);
        botaoSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarActionPerformed(evt);
            }
        });

        botaoExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/delete_32.png"))); // NOI18N
        botaoExcluir.setToolTipText("Excluir");
        botaoExcluir.setBorder(null);
        botaoExcluir.setContentAreaFilled(false);
        botaoExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoExcluir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/delete2_32.png"))); // NOI18N
        botaoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirActionPerformed(evt);
            }
        });

        botaoAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/backward_32.png"))); // NOI18N
        botaoAnterior.setToolTipText("Anterior");
        botaoAnterior.setBorder(null);
        botaoAnterior.setContentAreaFilled(false);
        botaoAnterior.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoAnterior.setEnabled(false);
        botaoAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAnteriorActionPerformed(evt);
            }
        });

        botaoPrimeiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/backwardFirst_32.png"))); // NOI18N
        botaoPrimeiro.setToolTipText("Primeiro");
        botaoPrimeiro.setBorder(null);
        botaoPrimeiro.setContentAreaFilled(false);
        botaoPrimeiro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoPrimeiro.setEnabled(false);
        botaoPrimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPrimeiroActionPerformed(evt);
            }
        });

        botaoUltimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/forwardEnd_32.png"))); // NOI18N
        botaoUltimo.setToolTipText("Último");
        botaoUltimo.setBorder(null);
        botaoUltimo.setContentAreaFilled(false);
        botaoUltimo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoUltimoActionPerformed(evt);
            }
        });

        botaoProximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/forward_32.png"))); // NOI18N
        botaoProximo.setToolTipText("Próximo");
        botaoProximo.setBorder(null);
        botaoProximo.setContentAreaFilled(false);
        botaoProximo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoProximoActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(153, 153, 153));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout painelManterLayout = new javax.swing.GroupLayout(painelManter);
        painelManter.setLayout(painelManterLayout);
        painelManterLayout.setHorizontalGroup(
            painelManterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelManterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botaoNovo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(botaoPrimeiro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoAnterior)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoProximo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoUltimo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelManterLayout.setVerticalGroup(
            painelManterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelManterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelManterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoSalvar)
                    .addComponent(botaoExcluir)
                    .addComponent(botaoNovo)
                    .addGroup(painelManterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(painelManterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botaoAnterior)
                            .addComponent(botaoPrimeiro)
                            .addComponent(botaoProximo)
                            .addComponent(botaoUltimo))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText("Código:");

        tfCodigo.setEditable(false);

        jLabel2.setText("Nome:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelManter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 367, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelManter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoNovoActionPerformed
        limparFormulario();
    }//GEN-LAST:event_botaoNovoActionPerformed

    private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarActionPerformed
        if (tfNome.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Preencha os campos obrigatórios!", "Aviso", JOptionPane.INFORMATION_MESSAGE, new ImageIcon(getClass().getResource("/view/img/sad_32.png")));
            tfNome.requestFocus();
        } else {
            if (tfCodigo.getText().isEmpty()) {
                salvar();
            } else {
                atualizar();
            }
            parent.setListaFuncoes(listaFuncoes);
            parent.preencherTabela();
            atualizarFormulario();
        }
    }//GEN-LAST:event_botaoSalvarActionPerformed

    private void botaoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirActionPerformed
        int resposta = JOptionPane.showConfirmDialog(this, "Deseja Excluir?", "Confirmar", JOptionPane.YES_NO_OPTION);
        if (resposta == 0) {
            //se ao excluir retornar true, então atualiza a lista
            if (dao.deletarFuncao(funcao.getId())) {
                listaFuncoes = dao.getAllFuncoes(parent.getOrdenacao());
                posicao = 0;
                funcao = listaFuncoes.get(posicao);
                JOptionPane.showMessageDialog(this, "Excluído com Sucesso!", "Aviso", JOptionPane.INFORMATION_MESSAGE, new ImageIcon(getClass().getResource("/view/img/success_32.png")));
            }

            parent.setListaFuncoes(listaFuncoes);
            parent.preencherTabela();
            atualizarFormulario();
        }

    }//GEN-LAST:event_botaoExcluirActionPerformed

    private void botaoAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAnteriorActionPerformed
        posicao--;
        if (posicao < 0) {
            JOptionPane.showMessageDialog(this, "Início da lista!", "Aviso", JOptionPane.INFORMATION_MESSAGE, new ImageIcon(getClass().getResource("/view/img/sad_32.png")));
            posicao++;
        } else {
            funcao = listaFuncoes.get(posicao);
            atualizarFormulario();
        }

    }//GEN-LAST:event_botaoAnteriorActionPerformed

    private void botaoPrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPrimeiroActionPerformed
        posicao = 0;
        funcao = listaFuncoes.get(posicao);
        atualizarFormulario();

    }//GEN-LAST:event_botaoPrimeiroActionPerformed

    private void botaoUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoUltimoActionPerformed
        posicao = listaFuncoes.size() - 1;
        funcao = listaFuncoes.get(posicao);
        atualizarFormulario();
    }//GEN-LAST:event_botaoUltimoActionPerformed

    private void botaoProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoProximoActionPerformed
        posicao++;
        if (posicao > listaFuncoes.size() - 1) {
            JOptionPane.showMessageDialog(this, "Final da lista!", "Aviso", JOptionPane.INFORMATION_MESSAGE, new ImageIcon(getClass().getResource("/view/img/sad_32.png")));
            posicao--;
        } else {
            funcao = listaFuncoes.get(posicao);
            atualizarFormulario();
        }

    }//GEN-LAST:event_botaoProximoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAnterior;
    private javax.swing.JButton botaoExcluir;
    private javax.swing.JButton botaoNovo;
    private javax.swing.JButton botaoPrimeiro;
    private javax.swing.JButton botaoProximo;
    private javax.swing.JButton botaoSalvar;
    private javax.swing.JButton botaoUltimo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel painelManter;
    private javax.swing.JTextField tfCodigo;
    private javax.swing.JTextField tfNome;
    // End of variables declaration//GEN-END:variables

    public static void main(String[] args) {
        new DialogFuncao(new InternalFuncao(), true).setVisible(true);
    }

    private void atualizarFormulario() {
        tfCodigo.setText(funcao.getId() + "");
        tfNome.setText(funcao.getNome());

        botaoExcluir.setEnabled(true);

        if (posicao == 0) {
            botaoAnterior.setEnabled(false);
            botaoPrimeiro.setEnabled(false);
            botaoProximo.setEnabled(true);
            botaoUltimo.setEnabled(true);
        } else if (posicao == listaFuncoes.size() - 1) {
            botaoAnterior.setEnabled(true);
            botaoPrimeiro.setEnabled(true);
            botaoProximo.setEnabled(false);
            botaoUltimo.setEnabled(false);
        } else {
            botaoAnterior.setEnabled(true);
            botaoPrimeiro.setEnabled(true);
            botaoProximo.setEnabled(true);
            botaoUltimo.setEnabled(true);
        }
    }

    private void limparFormulario() {
        posicao = -1;
        botaoAnterior.setEnabled(false);
        botaoPrimeiro.setEnabled(false);

        tfCodigo.setText("");
        tfNome.setText("");

        tfNome.requestFocus(); //coloca o caret dentro do campo
        botaoExcluir.setEnabled(false);
    }

    private void salvar() {
        Funcao f = new Funcao();
        f.setNome(tfNome.getText());

        //Se salvar retornar true, é porque houve sucesso ao salvar
        if (dao.insertFuncao(f)) {
            listaFuncoes = dao.getAllFuncoes(parent.getOrdenacao());
            int i = 0;
            for(Funcao fun : listaFuncoes){
                if(fun.getNome().equals(f.getNome())){
                    funcao = fun;
                    posicao = i;
                }
                i++;
            }
            JOptionPane.showMessageDialog(this, "Salvo com Sucesso!", "Aviso!", JOptionPane.INFORMATION_MESSAGE, new ImageIcon(getClass().getResource("/view/img/success_32.png")));
        }
    }

    private void atualizar() {
        Funcao f = new Funcao();
        f.setId(Integer.parseInt(tfCodigo.getText()));
        f.setNome(tfNome.getText());

        //se ao atualizar retornar true, então atualiza a lista
        if (dao.atualizarFuncao(f)) {
            listaFuncoes = dao.getAllFuncoes(parent.getOrdenacao());
            funcao = listaFuncoes.get(posicao);
            JOptionPane.showMessageDialog(this, "Atualizado com Sucesso!", "Aviso", JOptionPane.INFORMATION_MESSAGE, new ImageIcon(getClass().getResource("/view/img/success_32.png")));
        }
    }
}
