/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.DAOFuncionario;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.Funcionario;

/**
 *
 * @author Eliomar
 */
public class InternalFuncionario extends javax.swing.JInternalFrame {

    private DAOFuncionario dao;
    private List<Funcionario> listaFuncionarios;
    private Funcionario funcionario;
    private int linhaSelecionada;
    private String ordenacao;
    
    public InternalFuncionario() {
        initComponents();
        ordenacao = "funci_nome";
        dao = new DAOFuncionario();
        listaFuncionarios = dao.getAllFuncionarios(ordenacao);
        linhaSelecionada = 0;
        if(listaFuncionarios.isEmpty() == false){
             funcionario = listaFuncionarios.get(linhaSelecionada); 
             preencherTabela();
        }      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        btExcluir = new javax.swing.JButton();
        btNovo = new javax.swing.JButton();
        btAbrir = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        rbNome = new javax.swing.JRadioButton();
        rbCodigo = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        cbFiltrar = new javax.swing.JComboBox<String>();
        tfFiltrar = new javax.swing.JTextField();
        btFiltrar = new javax.swing.JButton();
        btLimparFiltrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Lista de Funcionários");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/office_24.png"))); // NOI18N

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Ações"));

        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/delete_32.png"))); // NOI18N
        btExcluir.setToolTipText("Excluir");
        btExcluir.setBorder(null);
        btExcluir.setContentAreaFilled(false);
        btExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btExcluir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/delete2_32.png"))); // NOI18N
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/new2_32.png"))); // NOI18N
        btNovo.setToolTipText("Novo");
        btNovo.setBorder(null);
        btNovo.setContentAreaFilled(false);
        btNovo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btNovo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/new3_32.png"))); // NOI18N
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });

        btAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/folder_32.png"))); // NOI18N
        btAbrir.setToolTipText("Abrir");
        btAbrir.setBorder(null);
        btAbrir.setContentAreaFilled(false);
        btAbrir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btAbrir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/folder2_32.png"))); // NOI18N
        btAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAbrirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(btNovo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btAbrir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btExcluir))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btNovo)
            .addComponent(btExcluir)
            .addComponent(btAbrir)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Ordenar"));

        buttonGroup1.add(rbNome);
        rbNome.setSelected(true);
        rbNome.setText("Nome");
        rbNome.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        rbNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNomeActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbCodigo);
        rbCodigo.setText("Código");
        rbCodigo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        rbCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCodigoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbCodigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbNome)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbCodigo)
                    .addComponent(rbNome))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtros"));

        cbFiltrar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nome", "Código" }));
        cbFiltrar.setToolTipText("Filtrar Por");

        tfFiltrar.setToolTipText("Digite para Filtrar");
        tfFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfFiltrarActionPerformed(evt);
            }
        });

        btFiltrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/filter_32.png"))); // NOI18N
        btFiltrar.setToolTipText("Filtrar");
        btFiltrar.setBorder(null);
        btFiltrar.setContentAreaFilled(false);
        btFiltrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btFiltrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/filter2_32.png"))); // NOI18N
        btFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFiltrarActionPerformed(evt);
            }
        });

        btLimparFiltrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/eraser2_32.png"))); // NOI18N
        btLimparFiltrar.setToolTipText("Limpar Filtro e Listar Tudo");
        btLimparFiltrar.setBorder(null);
        btLimparFiltrar.setContentAreaFilled(false);
        btLimparFiltrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btLimparFiltrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/eraser3_32.png"))); // NOI18N
        btLimparFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparFiltrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btFiltrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btLimparFiltrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btFiltrar)
            .addComponent(btLimparFiltrar)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(tfFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(cbFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Gerente"},
                {"2", "Estagiário"},
                {"3", "Vigilante"},
                {null, null}
            },
            new String [] {
                "Código", "Nome"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(231, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNomeActionPerformed
        ordenacao = "funci_nome";
        listaFuncionarios = dao.getAllFuncionarios(ordenacao);
        preencherTabela();
    }//GEN-LAST:event_rbNomeActionPerformed

    private void rbCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCodigoActionPerformed
        ordenacao = "funci_id";
        listaFuncionarios = dao.getAllFuncionarios(ordenacao);
        preencherTabela();
    }//GEN-LAST:event_rbCodigoActionPerformed

    private void tfFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfFiltrarActionPerformed

    }//GEN-LAST:event_tfFiltrarActionPerformed

    private void btFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFiltrarActionPerformed
        String campo = cbFiltrar.getSelectedItem().toString();
        if(campo.equals("Nome")){
            campo = "funci_nome";
        }else{
            campo = "funci_id";
        }

        String valor = tfFiltrar.getText();

        List<Funcionario> listaTemporaria = dao.getFiltrarFuncionarios(campo, valor, ordenacao);

        if(listaTemporaria.isEmpty()){
            JOptionPane.showMessageDialog(this, "Ops! não encontrei nada!");
        }else{
           listaFuncionarios = listaTemporaria;
           preencherTabela();
        } 
    }//GEN-LAST:event_btFiltrarActionPerformed

    private void btLimparFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparFiltrarActionPerformed
        listaFuncionarios = dao.getAllFuncionarios(ordenacao);
        jTable1.setRowSelectionInterval(0, 0);
        tfFiltrar.setText("");
        preencherTabela();
    }//GEN-LAST:event_btLimparFiltrarActionPerformed

    private void btAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAbrirActionPerformed
       new  DialogFuncionario(this, false).setVisible(true);
    }//GEN-LAST:event_btAbrirActionPerformed

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
       new  DialogFuncionario(this, true).setVisible(true);
    }//GEN-LAST:event_btNovoActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        int resposta = JOptionPane.showConfirmDialog(this, "Deseja Excluir?", "Confirmar", JOptionPane.YES_NO_OPTION);
        if (resposta == 0) {
            //se ao excluir retornar true, então atualiza a lista
            Funcionario f = listaFuncionarios.get(jTable1.getSelectedRow());
            if (dao.deletarFuncionario(f.getId()))  {
                listaFuncionarios = dao.getAllFuncionarios(ordenacao);
                funcionario = listaFuncionarios.get(0);
                JOptionPane.showMessageDialog(this, "Excluído com Sucesso!", "Aviso", JOptionPane.INFORMATION_MESSAGE, new ImageIcon(getClass().getResource("/view/img/success_32.png")));
            }

            preencherTabela();
            
        }
    }//GEN-LAST:event_btExcluirActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       if(evt.getClickCount() == 2){
           new  DialogFuncionario(this, false).setVisible(true);
       }
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAbrir;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btFiltrar;
    private javax.swing.JButton btLimparFiltrar;
    private javax.swing.JButton btNovo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbFiltrar;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton rbCodigo;
    private javax.swing.JRadioButton rbNome;
    private javax.swing.JTextField tfFiltrar;
    // End of variables declaration//GEN-END:variables

    public void preencherTabela() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setNumRows(0);
        Object[] linha;
        
        for(Funcionario f : listaFuncionarios){
            linha = new Object[]{f.getId(), f.getNome()};
            model.addRow(linha);
        }
        
        jTable1.setRowSelectionInterval(0, 0);
    }

    public void setListaFuncionarios(List<Funcionario> listaFuncionarios) {
        this.listaFuncionarios = listaFuncionarios;
    }

    public List<Funcionario> getListaFuncionarios() {
        return listaFuncionarios;
    }

    public JTable getjTable1() {
        return jTable1;
    }

    public String getOrdenacao(){
        return this.ordenacao;
    }
    

}
