/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package introducao;

import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author 201720040009
 */
public class Exemplo08 extends javax.swing.JFrame {

    /**
     * Creates new form Exemplo7
     */
    public Exemplo08() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jtfNomeUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtfAnoNascimento = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfAnoAtual = new javax.swing.JTextField();
        jlBoasVindas = new javax.swing.JLabel();
        jbtnCliqueAqui = new javax.swing.JButton();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Digite seu nome:");

        jtfNomeUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNomeUsuarioActionPerformed(evt);
            }
        });

        jLabel2.setText("Digite seu ano de nascimento:");

        jtfAnoNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfAnoNascimentoActionPerformed(evt);
            }
        });

        jLabel3.setText("Digite seu ano atual:");

        jtfAnoAtual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfAnoAtualActionPerformed(evt);
            }
        });

        jlBoasVindas.setText("Boas-Vindas!");

        jbtnCliqueAqui.setText("Clique Aqui");
        jbtnCliqueAqui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCliqueAquiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfAnoAtual))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfAnoNascimento))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(159, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jlBoasVindas)
                .addGap(40, 40, 40)
                .addComponent(jbtnCliqueAqui)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfAnoNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfAnoAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlBoasVindas)
                    .addComponent(jbtnCliqueAqui))
                .addContainerGap(183, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfNomeUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNomeUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNomeUsuarioActionPerformed

    private void jtfAnoNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfAnoNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfAnoNascimentoActionPerformed

    private void jtfAnoAtualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfAnoAtualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfAnoAtualActionPerformed

    private void jbtnCliqueAquiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCliqueAquiActionPerformed
        int anoAtual, anoNascimento, resultado;
        String nomeUsuario;

        Scanner teclado = new Scanner(System.in);

        nomeUsuario = jtfNomeUsuario.getText();
        anoAtual = Integer.parseInt(jtfAnoAtual.getText());
        anoNascimento = Integer.parseInt(jtfAnoNascimento.getText());
        resultado = anoAtual - anoNascimento;
        
        JOptionPane.showMessageDialog(this, "Seja bem vindo(a)"+nomeUsuario);
        
        if (resultado > 60) {
            jlBoasVindas.setText("Seja bem vindo(a) " + nomeUsuario + ", você está muito velho!! ");
        } else if (resultado >= 40 && resultado <= 60) {
            jlBoasVindas.setText("Seja bem vindo(a) " + nomeUsuario + ", você está ficando coroa!!");
        } else if (resultado < 40) {
            jlBoasVindas.setText("Seja bem vindo(a) " + nomeUsuario + ", você é jovem ainda amanhã velho será!!");
        }


    }//GEN-LAST:event_jbtnCliqueAquiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exemplo08.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exemplo08.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exemplo08.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exemplo08.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exemplo08().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JButton jbtnCliqueAqui;
    private javax.swing.JLabel jlBoasVindas;
    private javax.swing.JTextField jtfAnoAtual;
    private javax.swing.JTextField jtfAnoNascimento;
    private javax.swing.JTextField jtfNomeUsuario;
    // End of variables declaration//GEN-END:variables
}
